#   STAGE 1: Builder
FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json ./

RUN npm install 

COPY . .


#   STAGE 2: Final
FROM node:18-alpine

RUN apk update && \
    apk add --no-cache ca-certificates bash vim procps curl && \
    rm -rf /var/cache/apk/*

# Create a user and group with specific IDs (UID and GID 1500)
RUN addgroup -g 1500 user && \
    adduser -u 1500 -G user -h /home/user -D user

# Set HOME environment variable
ENV HOME=/home/user

# Set working directory and ensure proper ownership
WORKDIR /home/user
RUN chown -R user:user /home/user

# Copy the built artifacts from the builder stage
COPY --chown=user:user --from=builder /app /home/user

# Ensure start.sh is executable (if you use it)
RUN chmod +x ./start.sh

# Expose port 8080 if your application listens there
EXPOSE 8080

# Switch to the created user for security
USER user

ENTRYPOINT ["./start.sh"]
