apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "devops-assignment.fullname" . }}
  labels:
    app: {{ include "devops-assignment.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "devops-assignment.fullname" . }}

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
      
  template:
    metadata:
      labels:
        app: {{ include "devops-assignment.fullname" . }}
    spec:
      initContainers:
        - name: pre-deployment
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/bash", "-c", "echo Running pre-deployment tests; node k8s-test.js"]
      containers:
        - name: devops-assignment
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: "{{ .Values.environment.NODE_ENV }}"
          ports:
            - containerPort: {{ .Values.port }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
---
