apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-assignment.fullname" . }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "devops-assignment.fullname" . }}-mongo
  template:
    metadata:
      labels:
        app: {{ include "devops-assignment.fullname" . }}-mongo
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongo.image }}:{{ .Values.mongo.tag }}"
          imagePullPolicy: {{ .Values.mongo.pullPolicy }}
          ports:
            - containerPort: {{ .Values.mongo.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  selector:
    app: {{ include "devops-assignment.fullname" . }}-mongo
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
